require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/quests", type: :request do
  let(:valid_attributes) {
    { name: "Test Quest", status: false }
  }

  let(:invalid_attributes) {
    { name: "", status: false }
  }

  describe "GET /index" do
    it "renders a successful response" do
      get quests_path
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    let(:quest) { Quest.create!(name: "Test Quest", status: false) }

    it "renders a successful response" do
      get quest_path(quest)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_quest_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    let(:quest) { Quest.create!(name: "Test Quest", status: false) }

    it "renders a successful response" do
      get edit_quest_path(quest)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new quest" do
        expect {
          post quests_path, params: { quest: valid_attributes }
        }.to change(Quest, :count).by(1)
      end

      it "redirects to the created quest" do
        post quests_path, params: { quest: valid_attributes }
        expect(response).to redirect_to(quest_path(Quest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new quest" do
        expect {
          post quests_path, params: { quest: invalid_attributes }
        }.to change(Quest, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post quests_path, params: { quest: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    let(:quest) { Quest.create!(valid_attributes) }

    context "with valid parameters" do
      let(:new_attributes) {
        { name: "Updated Quest", status: true }
      }

      it "updates the requested quest" do
        patch quest_path(quest), params: { quest: new_attributes }
        quest.reload
        expect(quest.name).to eq("Updated Quest")
        expect(quest.status).to eq(true)
      end

      it "redirects to the quest" do
        patch quest_path(quest), params: { quest: new_attributes }
        quest.reload
        expect(response).to redirect_to(quest_path(quest))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patch quest_path(quest), params: { quest: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    let!(:quest) { Quest.create!(name: "Test Quest", status: false) }

    it "destroys the requested quest" do
      expect {
        delete quest_path(quest)
      }.to change(Quest, :count).by(-1)
      expect(response).to redirect_to(quests_path)
    end
  end
end
